spring:
  profiles:
    active: '@activatedProperties@'
---
spring:
  config:
    activate:
      on-profile: dev

sheet:
  name: "Arkusz1"
  isFirst: true
  gid: 0
---
spring:
  config:
    activate:
      on-profile: test

sheet:
  name: "Arkusz2"
  isFirst: false
  gid: 42467618